~ upgrade to `pytest 6.2.5`
'''test-requirements.txt''' √
› pytest==6.2.5

» Issue:

``` bash
(.venv) dragancajic@ubuntu:~/Devs/pytest-and-docker$ pytest
TypeError: required field "lineno" missing from alias
```

» Solution: :checkered_flag: ✔️

Pytest issues >> TypeError: required field "lineno" missing from alias · pytest-dev/pytest · Discussion #9195
https://github.com/pytest-dev/pytest/discussions/9195

Error running pytest: "TypeError: required field "lineno" missing from alias" · Issue #171 · tokenspice/tokenspice
https://github.com/tokenspice/tokenspice/issues/171

The fix is to force pytest >= 6.2.5
Details: pytest-dev/pytest#9195